name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # Checkout repo with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for SonarCloud to detect branches

      # Set up Java (required by SonarScanner)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache SonarCloud packages for faster runs
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask==3.0.3 prometheus-flask-exporter==0.23.1

      # Run SonarCloud scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          entryPoint: sonar-scanner
          args: >
            -Dsonar.projectKey=upload-server
            -Dsonar.organization=upload-server-sonarcloud
            -Dsonar.sources=upload-server
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
